[metadata]
name = f2py
version = 0.3.1.dev0
install_requires = [six]

author = 'Pearu Peterson'
author_email = 'pearu.peterson@gmail.com'

license = 'BSD'
description = The F2PY Project
long_description =
    The F2PY project is created to unify the efforts of supporting easy
    connection between Fortran and Python languages. The project will
    provide software, documentation, and support to solve a difficult task
    of automatically generating Python wrappers to Fortran libraries.

    The following packages are provided:

    fparser - Fortran 66/77/90/95/2003 parser

    The aim is to have a tool, called f2py, that can automatically
    generate Python wrappers to any Fortran program, be it written in
    Fortran 66/77 or in Fortran 90/95/2003.

    See http://code.google.com/p/f2py/ for more information.
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Intended Audience :: Science/Research
    License :: OSI Approved
    Natural Language :: English
    Programming Language :: C
    Programming Language :: Fortran
    Programming Language :: Python
    Topic :: Scientific/Engineering
    Topic :: Software Development
    Topic :: Software Development :: Code Generators
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX
    Operating System :: Unix
    Operating System :: MacOS
url = http://code.google.com/p/f2py/

[options]
py_modules = fparser

# vim: sw=4
